In [1]:
import torch

In [2]:
print(torch.__version__)

1.13.1+cu116


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# Introduction to Tensors

## Creating Tensors

### Scalar

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

### Vector

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.item

<function Tensor.item>

In [10]:
vector.shape

torch.Size([2])

### MATRIX

In [11]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

### TENSOR

In [16]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [20]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6657, 0.9103, 0.7360, 0.2683],
        [0.3209, 0.7967, 0.2347, 0.3955],
        [0.6258, 0.8657, 0.2039, 0.6814]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
len(random_tensor)

3

In [24]:
image_tensor = torch.rand(224,224,3)
image_tensor

tensor([[[0.1150, 0.3310, 0.9329],
         [0.8950, 0.6133, 0.8478],
         [0.4113, 0.6360, 0.4592],
         ...,
         [0.6778, 0.2312, 0.7013],
         [0.7099, 0.9738, 0.5866],
         [0.0186, 0.9656, 0.9172]],

        [[0.4035, 0.6290, 0.0767],
         [0.2672, 0.3230, 0.8439],
         [0.9028, 0.8438, 0.5592],
         ...,
         [0.3022, 0.6995, 0.2282],
         [0.8877, 0.0118, 0.3313],
         [0.6236, 0.1017, 0.7732]],

        [[0.2219, 0.7118, 0.7309],
         [0.6613, 0.7643, 0.5067],
         [0.8228, 0.3797, 0.0486],
         ...,
         [0.7959, 0.2133, 0.1526],
         [0.2900, 0.4647, 0.4703],
         [0.5190, 0.4489, 0.5053]],

        ...,

        [[0.9385, 0.8511, 0.4889],
         [0.3491, 0.0030, 0.7632],
         [0.1531, 0.8359, 0.4074],
         ...,
         [0.4731, 0.8385, 0.1126],
         [0.0800, 0.4733, 0.0838],
         [0.8018, 0.5463, 0.4523]],

        [[0.5017, 0.9682, 0.3495],
         [0.2747, 0.7299, 0.6508],
         [0.

In [25]:
image_tensor.ndim

3

In [26]:
image_tensor.shape

torch.Size([224, 224, 3])

In [27]:
image_tensor.size

<function Tensor.size>

In [28]:
tensor_zeros = torch.zeros(3,4)
tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
tensor_ones = torch.ones(3,4)
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
random_tensor * tensor_ones

tensor([[0.6657, 0.9103, 0.7360, 0.2683],
        [0.3209, 0.7967, 0.2347, 0.3955],
        [0.6258, 0.8657, 0.2039, 0.6814]])

In [31]:
random_tensor * tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
tensor_zeros.dtype

torch.float32

In [33]:
tensor_ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [34]:
range_tensor = torch.arange(1,1000,7)
range_tensor

tensor([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,  92,
         99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169, 176, 183, 190,
        197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267, 274, 281, 288,
        295, 302, 309, 316, 323, 330, 337, 344, 351, 358, 365, 372, 379, 386,
        393, 400, 407, 414, 421, 428, 435, 442, 449, 456, 463, 470, 477, 484,
        491, 498, 505, 512, 519, 526, 533, 540, 547, 554, 561, 568, 575, 582,
        589, 596, 603, 610, 617, 624, 631, 638, 645, 652, 659, 666, 673, 680,
        687, 694, 701, 708, 715, 722, 729, 736, 743, 750, 757, 764, 771, 778,
        785, 792, 799, 806, 813, 820, 827, 834, 841, 848, 855, 862, 869, 876,
        883, 890, 897, 904, 911, 918, 925, 932, 939, 946, 953, 960, 967, 974,
        981, 988, 995])

In [35]:
zeros = torch.zeros_like(range_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
torch.__version__

'1.13.1+cu116'

In [42]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device='cpu',
                               requires_grad=False)

In [50]:
float_32_tensor.dtype

torch.float64

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [54]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64,
                               device='cpu',
                               requires_grad=False)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [55]:
float_16_tensor.shape

torch.Size([3])

In [56]:
float_16_tensor.device

device(type='cpu')

In [57]:
float_64_tensor.dtype

torch.float64

In [58]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5782, 0.0937, 0.2246, 0.0306],
        [0.2554, 0.5241, 0.4330, 0.3963],
        [0.7652, 0.8391, 0.0470, 0.8828]])

In [59]:
some_tensor.dtype

torch.float32

In [60]:
some_tensor.shape

torch.Size([3, 4])

In [62]:
some_tensor.size()

torch.Size([3, 4])

In [63]:
some_tensor.device

device(type='cpu')

In [64]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [65]:
tensor + 10

tensor([11, 12, 13])

In [66]:
tensor * 10

tensor([10, 20, 30])

In [67]:
tensor

tensor([1, 2, 3])

In [68]:
tensor - 10

tensor([-9, -8, -7])

In [69]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [70]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [71]:
tensor * tensor

tensor([1, 4, 9])

In [72]:
torch.matmul(tensor, tensor)

tensor(14)

In [73]:
tensor.dot(tensor)

tensor(14)

In [74]:
tensor @ tensor

tensor(14)

In [75]:
tensor = torch.rand(3,4)

In [76]:
tensor

tensor([[0.8242, 0.5204, 0.3696, 0.0244],
        [0.9953, 0.3684, 0.2253, 0.1488],
        [0.2572, 0.9519, 0.3300, 0.3241]])

In [77]:
tensor.min()

tensor(0.0244)

In [79]:
tensor.max()

tensor(0.9953)

In [80]:
tensor.mean()

tensor(0.4450)

In [81]:
tensor.argmin()

tensor(3)

In [82]:
tensor.argmax()

tensor(4)

In [83]:
tensor.sum()

tensor(5.3396)

In [84]:
tensor.reshape(2,6)

tensor([[0.8242, 0.5204, 0.3696, 0.0244, 0.9953, 0.3684],
        [0.2253, 0.1488, 0.2572, 0.9519, 0.3300, 0.3241]])

In [86]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[5],
        [2],
        [3],
        [5],
        [5],
        [6],
        [5],
        [8],
        [9]])

In [90]:
x_reshaped.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
z = x.view(3,3)
z, z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), torch.Size([3, 3]))

In [93]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
z[:,0] = 5
z

tensor([[5, 2, 3],
        [5, 5, 6],
        [5, 8, 9]])

In [95]:
x

tensor([5, 2, 3, 5, 5, 6, 5, 8, 9])

In [98]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [99]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [5, 5, 5, 5],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [101]:
x_reshaped

tensor([[5],
        [2],
        [3],
        [5],
        [5],
        [6],
        [5],
        [8],
        [9]])

In [102]:
x_reshaped.squeeze()

tensor([5, 2, 3, 5, 5, 6, 5, 8, 9])

In [106]:
x_reshaped.unsqueeze(dim=1)

tensor([[[5]],

        [[2]],

        [[3]],

        [[5]],

        [[5]],

        [[6]],

        [[5]],

        [[8]],

        [[9]]])

In [107]:
x_original = torch.rand(size=(224,224,3))
x_original

tensor([[[0.4819, 0.3331, 0.5871],
         [0.5633, 0.7082, 0.3617],
         [0.7736, 0.9549, 0.7075],
         ...,
         [0.3443, 0.2906, 0.1765],
         [0.5350, 0.4196, 0.4947],
         [0.3340, 0.9399, 0.7677]],

        [[0.6613, 0.5573, 0.8010],
         [0.0073, 0.1660, 0.9020],
         [0.8555, 0.7562, 0.0265],
         ...,
         [0.7375, 0.7282, 0.0660],
         [0.5261, 0.1578, 0.4560],
         [0.0586, 0.0484, 0.3268]],

        [[0.4588, 0.4302, 0.0853],
         [0.9296, 0.6504, 0.0585],
         [0.6733, 0.6128, 0.5303],
         ...,
         [0.9823, 0.3706, 0.4007],
         [0.2717, 0.7248, 0.5535],
         [0.5097, 0.8761, 0.0092]],

        ...,

        [[0.4483, 0.8562, 0.3479],
         [0.7449, 0.4474, 0.1388],
         [0.0506, 0.3318, 0.8751],
         ...,
         [0.7221, 0.0287, 0.3327],
         [0.7151, 0.1812, 0.0202],
         [0.8893, 0.8792, 0.8584]],

        [[0.4944, 0.1213, 0.6316],
         [0.9576, 0.3064, 0.5820],
         [0.

In [108]:
x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.4819, 0.5633, 0.7736,  ..., 0.3443, 0.5350, 0.3340],
         [0.6613, 0.0073, 0.8555,  ..., 0.7375, 0.5261, 0.0586],
         [0.4588, 0.9296, 0.6733,  ..., 0.9823, 0.2717, 0.5097],
         ...,
         [0.4483, 0.7449, 0.0506,  ..., 0.7221, 0.7151, 0.8893],
         [0.4944, 0.9576, 0.9089,  ..., 0.6990, 0.7290, 0.9685],
         [0.3726, 0.7443, 0.6958,  ..., 0.3805, 0.1991, 0.1248]],

        [[0.3331, 0.7082, 0.9549,  ..., 0.2906, 0.4196, 0.9399],
         [0.5573, 0.1660, 0.7562,  ..., 0.7282, 0.1578, 0.0484],
         [0.4302, 0.6504, 0.6128,  ..., 0.3706, 0.7248, 0.8761],
         ...,
         [0.8562, 0.4474, 0.3318,  ..., 0.0287, 0.1812, 0.8792],
         [0.1213, 0.3064, 0.0513,  ..., 0.3339, 0.4125, 0.6309],
         [0.5379, 0.9518, 0.3157,  ..., 0.6465, 0.5400, 0.8149]],

        [[0.5871, 0.3617, 0.7075,  ..., 0.1765, 0.4947, 0.7677],
         [0.8010, 0.9020, 0.0265,  ..., 0.0660, 0.4560, 0.3268],
         [0.0853, 0.0585, 0.5303,  ..., 0.4007, 0.5535, 0.

In [109]:
x_permuted.shape

torch.Size([3, 224, 224])

In [110]:
tensor = torch.rand(4,5)
tensor

tensor([[0.8366, 0.8064, 0.2061, 0.3742, 0.2056],
        [0.7728, 0.3501, 0.8114, 0.1708, 0.1058],
        [0.4456, 0.9361, 0.4610, 0.7802, 0.7036],
        [0.5613, 0.5794, 0.9651, 0.7473, 0.2084]])

In [111]:
tensor[:,1]

tensor([0.8064, 0.3501, 0.9361, 0.5794])

In [112]:
tensor[2,:]

tensor([0.4456, 0.9361, 0.4610, 0.7802, 0.7036])

In [119]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [121]:
torch.rand(3,4)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [122]:
torch.cuda.is_available()

False

In [123]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [124]:
torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In [126]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')